apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/

patchesStrategicMerge:
- image-patch.yaml

images:
- name: us-east1-docker.pkg.dev/prod-prototype/default/rustyweb
  newTag: __REVISION__
